# Uncomment the next line to define a global platform for your project
platform :macos, '10.15'

target 'DevCycle-macOS-Example-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevCycle-Example-App
  pod 'DevCycle', :path => '../../'
end
