version: 2.1

jobs:
  test:
    macos:
      xcode: 12.0.0

    steps:
      - checkout
      - run: fastlane tests # Run tests using Fastlane

      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

workflows:
  ios-client-sdk:
    jobs:
      - test