# Uncomment the next line to define a global platform for your project
platform :tvos, '12.0'

target 'DevCycle-tvOS-Example-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevCycle-Example-App
  pod 'DevCycle', :path => '../../'
end
