# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DevCycle-Example-App-ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevCycle-Example-App-ObjC
  pod 'DevCycle'
end
