name: Semantic PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  pull-requests: read
jobs:
  check_title:
    name: Semantic PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@fdd4d3ddf614fbcd8c29e4b106d3bbe0cb2c605d
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_USER_TOKEN }}
