name: Build and Test iOS

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: "Select Latest Xcode"
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Verify Carthage Installation
        run: which carthage
      - name: Add Homebrew to PATH
        run: echo 'export PATH="/usr/local/bin:$PATH"' >> $GITHUB_ENV
      - name: "Carthage Cached Bootstrap"
        uses: DevCycleHQ/carthage-bootstrap@xcframeworks2
        with:
          github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          use-xcframeworks: true
      - name: Fastlane iOS Tests
        run: fastlane ios tests
