name: CocoaPods Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.**

permissions:
  contents: write

jobs:
  publish-cocoapods:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          fetch-depth: 0

      - name: Fix WatchOS Simulators
        run: |
          ./scripts/fix_watchos_simulators.sh

      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push DevCycle.podspec --allow-warnings --verbose

  wait-before-flutter-update:
    runs-on: ubuntu-latest
    needs: publish-cocoapods
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Wait for CocoaPods to update
        run: |
          # CocoaPods can be slow to update after publishing, so we wait 1 minute
          sleep 60

  update-flutter-sdk:
    runs-on: ubuntu-latest
    needs: wait-before-flutter-update
    steps:
      - name: Get latest tag
        id: get-tag
        run: |
          # Get the latest tag and strip the 'v' prefix
          LATEST_TAG=$(git ls-remote --tags --sort=version:refname https://github.com/DevCycleHQ/ios-client-sdk.git | tail -n1 | sed 's/.*\///;s/v//')
          echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Trigger Flutter SDK Update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update-ios-sdk-version.yaml
          repo: DevCycleHQ/flutter-client-sdk
          token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          inputs: '{"target-version": "${{ steps.get-tag.outputs.version }}"}'
