name: CocoaPods Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.**

permissions:
  contents: write
  pull-requests: write

jobs:
  publish-cocoapods:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          fetch-depth: 0

      - name: Fix WatchOS Simulators
        run: |
          ./scripts/fix_watchos_simulators.sh

      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push DevCycle.podspec --allow-warnings --verbose

  wait-before-flutter-update:
    runs-on: ubuntu-latest
    needs: publish-cocoapods
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Wait for CocoaPods to update
        run: |
          # CocoaPods can be slow to update after publishing, so we wait 1 minute
          sleep 60

      - name: Get version from tag
        id: get-version
        run: |
          # Strip the 'v' prefix from the tag name
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  update-flutter-sdk:
    uses: DevCycleHQ/flutter-client-sdk/.github/workflows/update-ios-sdk-version.yaml@main
    needs: wait-before-flutter-update
    permissions:
      contents: write
      pull-requests: write
    with:
      target-version: ${{ needs.wait-before-flutter-update.outputs.version }}
    secrets: inherit
