name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    name: Create GitHub Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Create Deployment
        uses: bobheadxi/deployments@v0.6.2
        id: deployment
        with:
          desc: Version Release
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: release
      - name: Set Deployment Status
        uses: bobheadxi/deployments@v0.6.2
        if: always()
        with:
          step: finish
          desc: Version Release
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}