name: Build and Test tvOS

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: "Select Latest Xcode"
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: "Carthage Cached Bootstrap"
        uses: DevCycleHQ/carthage-bootstrap@xcframeworks2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-xcframeworks: true
      - name: Fastlane tvOS Tests
        run: fastlane tvos tests