name: Build and Test tvOS

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: "Select Latest Xcode"
        uses: maxim-lobanov/setup-xcode@c51a66b42363123fa82a6cfe02c60af4281dab93
        with:
          xcode-version: latest-stable

      - name: "Carthage Cached Bootstrap"
        uses: DevCycleHQ/carthage-bootstrap@v1.2.0
        with:
          github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          use-xcframeworks: true

      - name: Fastlane tvOS Tests
        run: fastlane tvos tests
